import type {CollectionConfig, FieldHook} from 'payload'
import {generateSlugHook} from "@/collections/Articles/hooks/generate-slug-hook";
import {generateContentSummeryHook} from "@/collections/Articles/hooks/generate-content-summary.hook";
import {convertLexicalToPlaintext} from "@payloadcms/richtext-lexical/plaintext";

//fields
// - title
// - slug (autogenerated from title)
// - read_time_in_mins (auto-filled from content)
// - cover_image
// - author (relations)
// - status (drafts, published,)
// - published_at (only visible when status is published)


export const Config: CollectionConfig = {
    slug: 'articles',
    fields: [
        {
            name: 'title',
            type: 'text',
            required: true,
            unique:true,
        },
        {
            name: 'slug',
            type: 'text',
            required: true,
            unique: true,
            hooks: {beforeValidate: [generateSlugHook],}
        },
        {
            name: 'content',
            type:'richText',
            required: true,
        },
        {
            name: 'contentSummery',
            type:'textarea',
            required: true,
            hooks: { beforeValidate: [generateContentSummeryHook]}
        },
        {
            name:'readTimeInMins',
            type:'number',
            defaultValue:0,
            hooks: {
                beforeChange: [
                    ({siblingData}) => {
                        delete siblingData.readTimeInMins;
                    }
                ],
                afterRead: [
                    ({data}) => {
                        const text = convertLexicalToPlaintext({data: data?.content})
                        const wordsPerMinute = 200;
                        const words = text.trim().split(/\s+/).length
                        return Math.max(1, Math.ceil(words / wordsPerMinute))

                    }
                ]
            }
        }
    ]
}